import Head from "next/head";
import React from "react";
import { Header } from "../../app/components/Header";
import { Project } from "../../app/components/Project";
import TechnologyList from "../../app/components/Project/TechnologyList";

export const ProjectsPage = () => {
    const fullTime = <p className="bg-indigo-100 h-6 flex items-center justify-center text-indigo-800 text-xs font-semibold px-2.5 py-0.5 rounded">
        Full Time
    </p>

    const freelance = <p className="bg-teal-400 h-6 flex items-center text-cyan-900 text-xs font-semibold px-2.5 py-0.5 rounded">
        Freelance
    </p>

    const internship = <p className="bg-gray-100 h-6 flex items-center text-gray-800 text-xs font-semibold px-2.5 py-0.5 rounded">
        Internship
    </p>

    const personal =
        <p className="bg-blue-200 h-6 flex items-center justify-center text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded">
            Personal
        </p>

    const CompanyHyperLink = ({ name, url }: { name: string, url: string }) =>
        <div className="text-md flex justify-end mt-4">
            <a className="text-white text-center bg-blue-500 hover:bg-blue-600 rounded-sm px-3 text-md transition duration-300 ease-in-out" href={url} onClick={(e) => e.stopPropagation()} target="_blank" rel="noreferrer">
                {name}
            </a>
        </div>


    const projectsArray = [
        {
            projectTitle: "Form To Sheets",
            projectDescription: "Seamlessly integrate Google Forms into websites with code snippets for multiple frameworks",
            detailsPagePath: "/projects/formtosheets",
            featuredSkills: <TechnologyList technologies={["NextJS", "TailwindCSS", "Typescript"]} />,
            imagePath: "/projects-assets/formtosheets.png",
            projectType: personal,
        },
        {
            projectTitle: "Fubo Visualization Platform",
            projectDescription: "Built an internal tool for visualization of AI-generated sports videos and clips, optimizing analysis and evaluation procedures",
            detailsPagePath: "/projects/fubo-visualization-platform",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Emotion", "VideoJS", "Vite"]} />
                    <CompanyHyperLink name="Fubo" url="https://fubo.tv" />
                </>
            ),
            imagePath: "/projects-assets/internal-tool/1.jpeg",
            projectType: fullTime,
        },
        {
            projectTitle: "Instant Highlights",
            projectDescription: "Developed a cutting-edge feature enabling real-time display of instant highlights generated by AI during live NBA games",
            detailsPagePath: "/projects/instant-highlights",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Emotion", "Bitmovin Player", "Vitest", "RxJS"]} />
                    <CompanyHyperLink name="Fubo" url="https://fubo.tv" />
                </>
            ),
            projectType: fullTime,
        },
        {
            projectTitle: "Tapx",
            projectDescription: "A simple browser extension to search products from amazon.in from any webpage. Top amazon.in results for selected text in the webpage are shown in the popup.",
            detailsPagePath: "/projects/tapx",
            imagePath: "/projects-assets/tapx.png",
            featuredSkills: <TechnologyList technologies={["Svelte", "Go"]} />,
            projectType: personal,
        },
        {
            projectTitle: "Chakra Realty",
            projectDescription: "Built a real estate site to show properties, blogs and users to do due diligence on the properties they want to buy",
            detailsPagePath: "/projects/chakra-realty",
            imagePath: "/projects-assets/chakrarealty.jpeg",
            featuredSkills: <TechnologyList technologies={["React", "Next JS", "Tailwind CSS", "Python", "Scrapy"]} />,
            projectType: freelance,
        },
        {
            projectTitle: "Winuall Apps",
            projectDescription: "Built a feature to make the whole platform pluggable using Micro Frontend Architecture",
            detailsPagePath: "/projects/winuall-apps",
            imagePath: "/projects-assets/winuall-apps/1.png",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Styled Components", "Micro Frontend Architecture"]} />
                    <CompanyHyperLink name="Winuall" url="https://winuall.com" />
                </>
            ),
            projectType: fullTime,
        },
        {
            projectTitle: "Online Store",
            projectDescription: "Developed Online Store for tutors to create an E-Commerce store to sell books and courses",
            detailsPagePath: "/projects/winuall-online-store",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Styled Components", "Payment Gateways"]}/>
                    <CompanyHyperLink name="Winuall" url="https://winuall.com" />
                </>
            ),
            projectType: fullTime,
            imagePath: "/projects-assets/online-store/1.png",
        },
        {
            projectTitle: "Learner's module",
            projectDescription: "Single-handedly implemented a learner's module where students can learn the courses purchased by them",
            detailsPagePath: "/projects/winuall-learners-module",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Styled Components", "Redux"]}/>
                    <CompanyHyperLink name="Winuall" url="https://winuall.com" />

                </>
            ),
            projectType: fullTime,
            imagePath: "/projects-assets/learners-module/2.png",
        },
        {
            projectTitle: "New User Onboarding Flow",
            projectDescription: "Created a growth site for onboarding new users to the platform in a few clicks using NextJS",
            detailsPagePath: "/projects/user-registration-flow",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "NextJS", "Styled Components", "Context API"]}/>
                    <CompanyHyperLink name="Winuall" url="https://winuall.com" />

                </>
            ),
            projectType: fullTime,
            imagePath: "/projects-assets/user-reg-flow/1.png",
        },
        {
            projectTitle: "Winuall Parents Module",
            projectDescription: "Built a feature for parents to monitor their kids' performance",
            detailsPagePath: "/projects/winuall-parents-module",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Styled Components", "Redux"]}/>
                    <CompanyHyperLink name="Winuall" url="https://winuall.com" />

                </>
            ),
            projectType: fullTime,
        },
        {
            projectTitle: "Regcheck - Gatsby Site",
            projectDescription: "Built a gatsby site to view real-estate regulations of all the metropolitan cities in India",
            detailsPagePath: "/projects/regcheck",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "GatsbyJS", "GraphQL"]} />
                    <CompanyHyperLink name="Terra Economics and Analytics Labs" url="https://tealindia.in" />
                </>
            ),
            projectType: (
                internship
            ),
            imagePath: "/projects-assets/regcheck/1.png",
        },
        {
            projectTitle: "Printrove Admin Panel",
            projectDescription: "Built an internal tool for all the employees to update inventory and monitor incoming orders",
            hideAnchor: true,
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Redux", "Material UI"]} />
                    <CompanyHyperLink name="Printrove" url="https://printrove.com/" />
                </>
            ),
            projectType: (
                internship
            ),
        },
        {
            projectTitle: "Printrove Merchant Panel",
            projectDescription: "Contributed to many features for the users to build their dropshipping business",
            hideAnchor: true,
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React", "Redux", "Material UI"]} />
                    <CompanyHyperLink name="Printrove" url="https://printrove.com/" />
                </>
            ),
            projectType: (
                internship
            ),
        },
        {
            projectTitle: "No Paper Exams",
            projectDescription: "Built a landing page and contributed to the main user dashboard for generating quiz from a set of questions in a spreadsheet",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["HTML", "CSS", "React", "Redux"]} />
                </>
            ),
            hideAnchor: true,
            projectType: freelance,
        },
        {
            projectTitle: "A For Atom",
            projectDescription: "Built a static site to show information regarding seed balls and their advantages.",
            detailsPagePath: "/projects/a-for-atom",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["HTML", "CSS"]} />
                </>
            ),
            projectType: freelance,
            imagePath: "/projects-assets/aforatom.png",
        },
        {
            projectTitle: "Memewizard",
            projectDescription: "Meme Wizard is a fun and creative web application that allows users to create and share hilarious memes with ease.",
            detailsPagePath: "/projects/memewizard",
            featuredSkills: (
                <>
                    <TechnologyList technologies={["React"]} />
                </>
            ),
            projectType: personal,
        },
    ];

    return (
        <div className="w-full  flex items-center flex-col h-full">
            <Head>
                <title>Sudharsan | Projects</title>
            </Head>
            <main className="max-w-6xl sm:p-10 p-4">
                <Header navContents={["home", "links", "resume"]} />
                <div className="flex flex-col items-center justify-center p-7">
                    <h1 className="md:leading-tight md:text-5xl text-4xl font-semibold">My <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-400 to-red-600">Projects</span></h1>
                    <p className="mt-3 sm:text-lg text-md text-gray-300">All the projects I have built</p>
                </div>
                <section className="flex flex-wrap gap-2 p-2">
                    {projectsArray.map((project, index) => (
                        <Project
                            key={index}
                            projectTitle={project.projectTitle}
                            projectDescription={project.projectDescription}
                            featuredSkills={project.featuredSkills}
                            projectType={project.projectType}
                            imagePath={project.imagePath}
                            hideAnchor={project.hideAnchor}
                            detailsPagePath={project.detailsPagePath}
                        />
                    ))}
                </section>
            </main>
        </div>
    );
};

export default ProjectsPage;
