import React from 'react';
import { Metadata } from 'next';
import Image from 'next/image';
import { Layers, Link as LinkIcon, FileText, Lightbulb, LineChart, Target } from 'lucide-react';
import ProjectPageLayout, {
  FeatureList,
  ProjectImageGallery,
  ProjectSection,
} from '@/components/modules/project-page-layout';

export const metadata: Metadata = {
  title: 'FactoStack Marketing Website | Sudharsan GS',
  description:
    'A marketing and SEO case study on building FactoStack.com with solution pages, comparison pages, tools, schema, analytics, and product-led conversion flows.',
};

const technologies = [
  { name: 'NextJS', icon: '/skills/nextjs.svg' },
  { name: 'TypeScript', icon: '/skills/typescript.svg' },
  { name: 'TailwindCSS', icon: '/skills/tailwind.svg' },
  { name: 'React', icon: '/skills/react.svg' },
];

const aiTools = [
  { name: 'Claude Code', icon: '/skills/claude.svg' },
  { name: 'Codex', icon: '/skills/codex.png' },
];

const features = [
  'Homepage messaging for Indian manufacturers with direct paths into free trial, demo booking, and WhatsApp conversations.',
  'Feature and solution pages for CRM, inventory, production, procurement, quality, and manufacturing-MSME use cases.',
  'Comparison pages such as vs Odoo, vs ERPNext, vs Tally, and vs Vyapar to target bottom-funnel search intent.',
  'Free acquisition tools including invoice generation, quote generation, production cost calculation, and project calculators.',
  'Blog and MDX publishing with route discovery in the sitemap and page-level metadata for content expansion.',
  'Canonical metadata, Open Graph, breadcrumb/software schema, and conversion tracking wired into a reusable marketing system.',
];

const highlights = [
  {
    title: 'Search-surface architecture, not a brochure site',
    description:
      'The repo is structured around a broad acquisition surface: homepage, feature pages, solution pages, comparison routes, blog pages, and free tools. It is built to earn different kinds of intent instead of depending on a single homepage funnel.',
  },
  {
    title: 'SEO foundations built into the app layer',
    description:
      'The marketing site has reusable metadata helpers, canonical URLs, Open Graph tags, JSON-LD helpers for breadcrumbs, blog posts, and software pages, plus an autogenerated sitemap that includes app routes and blog content.',
  },
  {
    title: 'Measured conversion paths',
    description:
      'The site is not just content. Trial, demo, WhatsApp, quote flow, and calculator interactions are instrumented so the acquisition work can be measured, not guessed.',
  },
];

const results = [
  'Turned FactoStack.com into the marketing layer for the product, not a separate brand site with generic copy.',
  'Created reusable SEO and content primitives that support feature pages, industry pages, comparisons, blog posts, and tools from one codebase.',
  'Connected product storytelling directly to trial, demo, and WhatsApp handoffs into the live platform.',
  'Built a system that can keep expanding with new pages and tools without rewriting metadata, schema, or tracking each time.',
];

const screenshots = [
  {
    url: '/projects/personal/factostack-website/executive-dashboard.png',
    alt: 'FactoStack product preview on the website',
    caption: 'Embedded dashboard previews that make the product tangible inside the marketing site.',
  },
  {
    url: '/projects/personal/factostack-website/procurement-dashboard.png',
    alt: 'FactoStack procurement dashboard preview',
    caption: 'Module-specific product storytelling used across feature and solution pages.',
  },
];

export default function FactoStackWebsitePage() {
  return (
    <ProjectPageLayout
      title="FactoStack Marketing Website"
      description="The acquisition site for FactoStack, built as the marketing and SEO engine for a complex manufacturing product with search, tools, content, and conversion paths working together."
      type="personal"
      date="2025-2026"
      liveUrl="https://factostack.com"
    >
      <div className="mb-12 overflow-hidden rounded-2xl border border-primary/20">
        <Image
          src="/projects/personal/factostack-website/cover.png"
          alt="FactoStack website cover"
          width={1200}
          height={675}
          className="w-full h-auto"
          priority
        />
      </div>

      <ProjectSection title="Tech Stack" icon={<Layers className="w-5 h-5" />}>
        <div className="flex flex-wrap gap-3">
          {technologies.map((tech) => (
            <div
              key={tech.name}
              className="inline-flex items-center bg-card/80 shadow-sm rounded-full px-4 py-2 text-sm border border-primary/20"
            >
              <Image src={tech.icon} alt={tech.name} width={16} height={16} className="mr-2" />
              <span className="text-muted-foreground">{tech.name}</span>
            </div>
          ))}
        </div>
      </ProjectSection>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
        <ProjectSection
          title="The Problem"
          icon={<Lightbulb className="w-5 h-5" />}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          iconBorder="border-primary/20"
          className="mb-6 md:mb-0"
        >
          <p className="text-muted-foreground">
            FactoStack is a broad product, so a five-page brochure site would not be enough. The website had to explain the product clearly, capture search intent across multiple modules and industries, and move visitors into trial, demo, or WhatsApp conversations.
          </p>
        </ProjectSection>

        <ProjectSection
          title="The Solution"
          icon={<Target className="w-5 h-5" />}
          iconBg="bg-primary/10"
          iconColor="text-primary"
          iconBorder="border-primary/20"
          className="mb-0"
        >
          <p className="text-muted-foreground">
            I built the website as a marketing system: homepage positioning for Indian MSMEs, module and solution pages, comparison pages, free tools, blog routes, structured SEO, and analytics-backed handoffs into the live app and sales flows.
          </p>
        </ProjectSection>
      </div>

      <ProjectSection
        title="What The Site Covers"
        icon={<LinkIcon className="w-5 h-5" />}
      >
        <FeatureList
          items={features}
          iconBg="bg-primary/10"
          iconColor="text-primary"
        />
      </ProjectSection>

      <ProjectSection
        title="Implementation Highlights"
        icon={<FileText className="w-5 h-5" />}
        iconBg="bg-primary/10"
        iconColor="text-primary"
        iconBorder="border-primary/20"
      >
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {highlights.map((highlight) => (
            <div key={highlight.title} className="bg-primary/5 border border-primary/20 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2 text-primary">{highlight.title}</h3>
              <p className="text-muted-foreground">{highlight.description}</p>
            </div>
          ))}
        </div>
      </ProjectSection>

      <ProjectSection
        title="AI-Assisted Engineering"
        icon={<FileText className="w-5 h-5" />}
        iconBg="bg-primary/10"
        iconColor="text-primary"
        iconBorder="border-primary/20"
      >
        <div className="flex flex-wrap gap-3 mb-4">
          {aiTools.map((tool) => (
            <div
              key={tool.name}
              className="inline-flex items-center bg-card/80 shadow-sm rounded-full px-4 py-2 text-sm border border-primary/20"
            >
              <Image src={tool.icon} alt={tool.name} width={16} height={16} className="mr-2" />
              <span className="text-muted-foreground">{tool.name}</span>
            </div>
          ))}
        </div>
        <p className="text-muted-foreground">
          I also used Claude Code and Codex as AI-assisted engineering tools on the website. They helped speed up page implementation, metadata and schema patterns, iterative copy updates, and repetitive frontend work, while I kept the positioning, SEO direction, and final editorial judgment grounded in the product itself.
        </p>
      </ProjectSection>

      <ProjectSection title="Selected Screens" icon={<Layers className="w-5 h-5" />}>
        <ProjectImageGallery images={screenshots} columns={2} />
      </ProjectSection>

      <ProjectSection
        title="Results & Impact"
        icon={<LineChart className="w-5 h-5" />}
        iconBg="bg-primary/10"
        iconColor="text-primary"
        iconBorder="border-primary/20"
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {results.map((result) => (
            <div key={result} className="bg-primary/5 border border-primary/20 rounded-lg p-4">
              <p className="text-muted-foreground">{result}</p>
            </div>
          ))}
        </div>
      </ProjectSection>
    </ProjectPageLayout>
  );
}
