import { Experience } from '@/types/experience'

export const experiences: Experience[] = [
  {
    id: "fubo",
    title: "Software Engineer - Web",
    company: "Fubo",
    companyLogo: "/fubo.svg",
    companyUrl: "https://www.fubo.tv/",
    location: "Bengaluru, India",
    type: "Full Time",
    description: "Currently working on the Molotov TV team, the leading French OTT platform, focusing on enhancing the user experience for live sports streaming and improving the marketing site for better SEO. My role involves developing innovative features, improving video playback performance, and optimizing web presence. Previously, I was part of the VideoAI team, where I contributed to building AI-driven features for sports video analysis",
    period: {
      start: "Oct 2022",
      end: "Present"
    },
    achievements: [
      "Developed a cutting-edge feature enabling real-time display of instant highlights generated by AI during live NBA games.",
      "Built Timeline Markers feature to enhance user experience by enabling users to hover over highlighted moments while watching recorded games, offering seamless navigation to key events.",
      "Created a visualization platform that enabled 40% faster analysis of AI-generated sports videos, highlights, and moments.",
      "Implemented frame-accurate seeking in VideoJS for HLS and DASH videos, ensuring precise video playback and an improved user experience.",
      "Developed multiple POCs for VideoAI features using methodologies such as Server Driven UI and Micro Frontend Architecture."
    ],
    technologies: ["React", "TypeScript", "VideoJS", "Shaka Player", "GCP", "Docker", "Circle CI"],
    projects: []
  },
  {
    id: "winuall",
    title: "SDE 1",
    company: "Winuall",
    companyLogo: "/winuall.jpg",
    companyUrl: "https://winuall.com/",
    location: "Bengaluru, India",
    type: "Full Time",
    description: "Led frontend development for multiple EdTech projects, focusing on building scalable and high-performance web applications for tutors and learners. Worked directly with C-level executives to define product roadmaps.",
    period: {
      start: "Dec 2020",
      end: "Oct 2022"
    },
    achievements: [
      "Built an Online Store for tutors to create an E-Commerce platform using ReactJS and styled-components, serving 2000+ tutors.",
      "Implemented user onboarding system with NextJS, successfully onboarding 3000+ paying users.",
      "Achieved 30% performance improvement through Code Splitting and Lazy Loading techniques.",
      "Migrated legacy React application to SSR, improving SEO score by 60%.",
      "Established CI/CD pipeline using Github Actions and Docker for automated deployments."
    ],
    technologies: ["React", "NextJS", "TypeScript", "ExpressJS", "NodeJS", "Golang", "Docker", "AWS", "Azure"],
    projects: ["winuall-apps", "winuall-learners-module", "winuall-online-store", "winuall-marketing-site", "winuall-parents-module"],
    projectDescriptions: {
      "winuall-apps": "Developed a central hub for Winuall's web applications, allowing users to access different modules and features from a unified interface.",
      "winuall-learners-module": "Built a comprehensive learning platform for students with features like video courses, quizzes, and progress tracking.",
      "winuall-online-store": "Created an e-commerce platform enabling tutors to sell digital and physical products to their students.",
      "winuall-marketing-site": "Developed the company's main marketing website with SSR for improved SEO and performance.",
      "winuall-parents-module": "Built a dashboard for parents to track their children's learning progress and communicate with tutors."
    }
  },
  {
    id: "teal",
    title: "Frontend Developer - Intern",
    company: "TEAL",
    companyLogo: "/teal.ico",
    companyUrl: "https://www.tealindia.in/",
    location: "Bengaluru, India",
    type: "Internship",
    description: "Worked on developing consumer-facing web applications from scratch, focusing on performance and testing. Implemented headless CMS solutions with modern frontend frameworks.",
    period: {
      start: "Aug 2020",
      end: "Dec 2020"
    },
    achievements: [
      "Involved in building Tealcheck (B2C product) from scratch.",
      "Created and deployed Regcheck using Ghost CMS and Gatsby.",
      "Wrote E2E test cases using Cypress, achieving 90% test coverage."
    ],
    technologies: ["React", "Gatsby", "Ghost CMS", "Cypress"],
    projects: ["regcheck"],
    projectDescriptions: {
      "regcheck": "A vehicle registration information platform that provides users with details about their registered vehicles, built with Gatsby and Ghost CMS for content management."
    }
  },
  {
    id: "printrove",
    title: "Frontend Developer - Intern",
    company: "Printrove",
    companyLogo: "/printrove.png",
    companyUrl: "https://www.printrove.com/",
    location: "Chennai, India",
    type: "Internship",
    description: "Built internal admin tools and dashboards for a print-on-demand startup, focusing on automating workflows and improving operational efficiency.",
    period: {
      start: "Jun 2020",
      end: "July 2020"
    },
    achievements: [
      "Developed a dashboard for Printrove's internal use, enabling 100% automation of the order processing system.",
      "Developed a full-fledged accessory design simulation suite that 15000+ designers and Shopify merchants use.",
      "Created a merchant dashboard for Printrove's print-on-demand platform, allowing sellers to manage their products and orders efficiently."
    ],
    technologies: ["React", "Redux"],
    projects: ["printrove-admin-panel","printrove-merchant-panel"],
    projectDescriptions: {
      "printrove-admin-panel": "An internal administrative dashboard for Printrove's team to manage orders, products, and customer data with automated order processing.",
      "printrove-merchant-panel": "A dashboard for Printrove's merchants to manage their products, track sales, and handle customer inquiries."
    }
  }
]

